image: mcr.microsoft.com/dotnet/sdk:6.0

before_script:
  - dotnet restore
  
pages:
  stage: deploy
  script:
  - mkdir public
  - dotnet publish -c Release -o output
  - echo "Printing folders" && ls
  - cp -a /builds/ilmhub/akiss/output/* ./public
  - sed -i 's/<base href="\/" \/>/<base href="\/akiss\/" \/>/g' ./public/wwwroot/index.html
  - cat ./public/wwwroot/index.html
  artifacts:
    paths:
    - public
  only:
  - main